WIP - Update the content for Nonprofit pages/review-entity-type/nonprofit.js (Do Not Merge)
Riotters/incfile-test pull request #1
Opened 2020-09-08 22:19 UTC by tinapc

## What Does This Do?
- Update the content for Nonprofit pages/review-entity-type/nonprofit.js

2020-09-08 22:20 UTC, tinapc commented
@krzysiekstefanski  Could you plz take a review? I can show you a video to preview if you dont have a chance to see what I did done.

2020-09-10 04:52 UTC, Riotters requested changes

2020-09-10 04:52 UTC, Riotters commented on src/atomic/organisms/accordion/accordion-with-counting.js
> +const ListItems = styled.div`
ListItems should be ul, there's no need to create another div.

2020-09-10 04:52 UTC, Riotters commented on src/atomic/atoms/styles/colors.js
> +  grey6: "#63666e",
Palette is already done, use closest color.

2020-09-10 04:52 UTC, Riotters commented on src/atomic/sections/general/cta.js
> +          {({ isVisible }) => <Button className={isVisible ? "slideUp enter" : "slideUp"} content={{ text: `${cta.button.text || `Start Now`}`, url: `${cta.button.url || `#`}` }} theme="primary56" ar
For now, all urls should lead to the home page.

2020-09-10 04:52 UTC, Riotters commented on src/static/review-entity-type/c-corporation.js
> +      url: "https://www.incfile.com/form-order-now.php?entityType=CCorporation",
Sholud stay "/" for now.

2020-09-10 04:52 UTC, Riotters commented on src/static/review-entity-type/nonprofit.js
> +		url: `https://www.incfile.com/form-order-now.php?entityType=Nonprofit`,
"/" :)

2020-09-10 04:52 UTC, Riotters commented on src/static/review-entity-type/nonprofit.js
> +    url: `https://www.incfile.com/form-order-now.php?entityType=Nonprofit`,
"/" :)

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <p>While anyone can incorporate as a nonprofit, only those who pass the stringent standards set forth by the government can achieve tax exempt, or 501c3, status. The process of creati
import text from external, change to components heading, paragraph from atmos/typography

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <p style={{ marginTop: 48 + "px" }}>All other steps associated with Incorporation apply to the creation of a nonprofit organization, such as paying fees, registering for business loca
import, change to components

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <p style={{ marginTop: 48 + "px" }}>Political parties are also eligible for tax exempt status, but do not fall under the standard nonprofit category.</p>
import as text2

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <p>{content.content[2].text}</p>
change to components

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <h3>Don't get stuck, let us help you navigate the process.</h3>
import, change to components

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <p>{content.content[5].text}</p>
change to components

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <p>{content.content[6].text}</p>
change to components

2020-09-10 04:52 UTC, Riotters commented on src/components/about-tabs.js
> +                <h3>{content.content[7].header}</h3>
change to components

2020-09-10 13:19 UTC, Riotters approved these changes

2020-09-10 13:19 UTC, merged